
highlighter: pygments

relative_permalinks: true
permalink:   /blog/:year/:month/:day/:title.html

paginate_path: 'page:num'

markdown:      kramdown # redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile


excerpt_separator: "\n\n"


maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM

redcloth:
  hard_breaks: true


name: Aeol Kong
pygments: true

safe: true
lsi: false

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
